version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - dependencies
    commit-message:
      prefix: "deps(cicd)"

  - package-ecosystem: terraform
    directory: /bootstrap/backend
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(bootstrap)"

  - package-ecosystem: terraform
    directory: /bootstrap/github-oidc
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(bootstrap)"

  - package-ecosystem: terraform
    directory: /shared
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(shared)"

  - package-ecosystem: terraform
    directory: /envs/dev
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(dev)"
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - version-update:semver-major

  - package-ecosystem: terraform
    directory: /envs/prod
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(prod)"
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - version-update:semver-major

  - package-ecosystem: terraform
    directory: /modules/karpenter
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "deps(karpenter)"
