version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - dependencies
    commit-message:
      prefix: "deps(cicd)"

  - package-ecosystem: terraform
    directories:
      - /bootstrap/backend
      - /bootstrap/github-oidc
      - /shared
      - /envs/dev
      - /envs/prod
      - /modules/karpenter
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 3
    groups:
      terraform:
        patterns:
          - "*"
    labels:
      - dependencies
    commit-message:
      prefix: "deps(terraform)"
